#shape of gripper when opened --> values of gripper joints when gripper is opened (in the same order listed in group) 
open_gripper: [0, 1.047197551, 1.047197551]  #60 deg max opening angle 

#names of gripper joints involved in closing the gripper  
close_gripper_joints: ['gripper_left_joint', 'gripper_right_joint']

#maximum value for gripper joint when opened --> same value from above 
max_open_gripper_joint_value: 1.047197551

#distance between gripper jaws when fully opened    
max_open_length: 0.7

#tolerence for gripper closing 
close_gripper_tolerance: 0.01

#eef parent link in test block frame obtained from grasp config script
eef_parent_link_pregrasp_orientation: [0.0, -0.707, 0.0, 0.707]

#axis of approach of eef parent link 
approach_motion_axis: 'z'

#direction of approach --> if direction is in the 
direction_of_approach: false








