#shape of gripper when opened --> values of gripper joints when gripper is opened (in the same order listed in group) 
open_gripper: [0, 1.047197551, 1.047197551]  #60 deg max opening angle 

#maximum value for gripper joint when opened --> same value from above 
a_max: 1.047197551

#distance between gripper jaws when fully opened    
L_max: 0.7

#tolerence for gripper closing 
tolerance: 0.01




